title:            Fraktur
tagline:          A break.
description:      Collection of thoughts.
canonical:        http://roozemond.github.io
baseurl:          /fraktur-simplified
encoding:         utf-8

# Owner/author information
owner:
  name:           LR
  avatar:         avatar.png
  bio:            "Tinkerer and thinker"


tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: rouge
#markdown:    kramdown


sass:
    style: :compressed


permalink:   /:categories/:title/

include: [".htaccess"]
exclude: ["CNAME", "LICENSE", "Gem*", "S3*txt", "*.bak", "*.sh", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "README", "features.md"]
